export Navigation from 'components/home/Navigation';
export Header from 'components/home/Header';
export HowItWorks from 'components/home/HowItWorks';
export CustomerSegment from 'components/home/CustomerSegment';
export Features from 'components/home/Features';
export Setup from 'components/home/Setup';
export Newsletter from 'components/home/Newsletter';
export Team from 'components/home/Team';
export Footer from 'components/home/Footer';