export dashboardOne from 'images/dashboard_1.png'
export ishan from 'images/ishan.jpg';
export neeraj from 'images/neeraj.jpg';
export gaurav from 'images/gaurav.jpg';
export slideOne from 'images/slide_bg_1.jpg';
export slideTwo from 'images/slide_bg_2.jpg';
export slideThree from 'images/slide_bg_3.jpg';
export ecommerce from 'images/ecommerce.jpg';
export services from 'images/services.jpg';
export product from 'images/product.png';